package com.computech.pojo;

public class AccoutAnt {
	
	
    @Override
	public String toString() {
		return "AccoutAnt [accNo=" + accNo + ", custNo=" + custNo + ", custName=" + custName + ", carCard=" + carCard
				+ ", wxlx=" + wxlx + ", zyfl=" + zyfl + ", fdjh=" + fdjh + ", startDate=" + startDate + ", endDate="
				+ endDate + ", glfl=" + glfl + ", fkfs=" + fkfs + ", pjlx=" + pjlx + ", rgf=" + rgf + ", clf=" + clf
				+ ", glf=" + glf + ", qtf=" + qtf + ", sj=" + sj + ", je=" + je + ", sl=" + sl + ", yhje=" + yhje
				+ ", ssje=" + ssje + ", jdr=" + jdr + ", deleteStatus=" + deleteStatus + ", lxr=" + lxr + ", custTel="
				+ custTel + ", carType=" + carType + ", balanceStatus=" + balanceStatus + ", comName=" + comName
				+ ", address=" + address + ", bankName=" + bankName + ", comAccNo=" + comAccNo + ", comTel=" + comTel
				+ ", comLxr=" + comLxr + ", remarks=" + remarks + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.ACC_NO
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String accNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.CUST_NO
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String custNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.CUST_NAME
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String custName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.CAR_CARD
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String carCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.WXLX
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String wxlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.ZYFL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String zyfl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.FDJH
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String fdjh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.START_DATE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.END_DATE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String endDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.GLFL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String glfl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.FKFS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String fkfs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.PJLX
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String pjlx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.RGF
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String rgf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.CLF
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String clf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.GLF
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String glf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.QTF
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String qtf;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.SJ
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String sj;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.JE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String je;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.SL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String sl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.YHJE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String yhje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.SSJE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String ssje;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.JDR
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String jdr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.DELETE_STATUS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.LXR
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String lxr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.CUST_TEL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String custTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.CAR_TYPE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String carType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.BALANCE_STATUS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String balanceStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.COM_NAME
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String comName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.ADDRESS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.BANK_NAME
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String bankName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.COM_ACC_NO
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String comAccNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.COM_TEL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String comTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.COM_LXR
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String comLxr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column accout_ant.REMARKS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    private String remarks;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.ACC_NO
     *
     * @return the value of accout_ant.ACC_NO
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getAccNo() {
        return accNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.ACC_NO
     *
     * @param accNo the value for accout_ant.ACC_NO
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setAccNo(String accNo) {
        this.accNo = accNo == null ? null : accNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.CUST_NO
     *
     * @return the value of accout_ant.CUST_NO
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.CUST_NO
     *
     * @param custNo the value for accout_ant.CUST_NO
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.CUST_NAME
     *
     * @return the value of accout_ant.CUST_NAME
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.CUST_NAME
     *
     * @param custName the value for accout_ant.CUST_NAME
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.CAR_CARD
     *
     * @return the value of accout_ant.CAR_CARD
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getCarCard() {
        return carCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.CAR_CARD
     *
     * @param carCard the value for accout_ant.CAR_CARD
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setCarCard(String carCard) {
        this.carCard = carCard == null ? null : carCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.WXLX
     *
     * @return the value of accout_ant.WXLX
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getWxlx() {
        return wxlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.WXLX
     *
     * @param wxlx the value for accout_ant.WXLX
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setWxlx(String wxlx) {
        this.wxlx = wxlx == null ? null : wxlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.ZYFL
     *
     * @return the value of accout_ant.ZYFL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getZyfl() {
        return zyfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.ZYFL
     *
     * @param zyfl the value for accout_ant.ZYFL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setZyfl(String zyfl) {
        this.zyfl = zyfl == null ? null : zyfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.FDJH
     *
     * @return the value of accout_ant.FDJH
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getFdjh() {
        return fdjh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.FDJH
     *
     * @param fdjh the value for accout_ant.FDJH
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setFdjh(String fdjh) {
        this.fdjh = fdjh == null ? null : fdjh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.START_DATE
     *
     * @return the value of accout_ant.START_DATE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.START_DATE
     *
     * @param startDate the value for accout_ant.START_DATE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setStartDate(String startDate) {
        this.startDate = startDate == null ? null : startDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.END_DATE
     *
     * @return the value of accout_ant.END_DATE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.END_DATE
     *
     * @param endDate the value for accout_ant.END_DATE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setEndDate(String endDate) {
        this.endDate = endDate == null ? null : endDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.GLFL
     *
     * @return the value of accout_ant.GLFL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getGlfl() {
        return glfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.GLFL
     *
     * @param glfl the value for accout_ant.GLFL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setGlfl(String glfl) {
        this.glfl = glfl == null ? null : glfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.FKFS
     *
     * @return the value of accout_ant.FKFS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getFkfs() {
        return fkfs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.FKFS
     *
     * @param fkfs the value for accout_ant.FKFS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setFkfs(String fkfs) {
        this.fkfs = fkfs == null ? null : fkfs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.PJLX
     *
     * @return the value of accout_ant.PJLX
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getPjlx() {
        return pjlx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.PJLX
     *
     * @param pjlx the value for accout_ant.PJLX
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setPjlx(String pjlx) {
        this.pjlx = pjlx == null ? null : pjlx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.RGF
     *
     * @return the value of accout_ant.RGF
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getRgf() {
        return rgf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.RGF
     *
     * @param rgf the value for accout_ant.RGF
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setRgf(String rgf) {
        this.rgf = rgf == null ? null : rgf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.CLF
     *
     * @return the value of accout_ant.CLF
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getClf() {
        return clf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.CLF
     *
     * @param clf the value for accout_ant.CLF
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setClf(String clf) {
        this.clf = clf == null ? null : clf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.GLF
     *
     * @return the value of accout_ant.GLF
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getGlf() {
        return glf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.GLF
     *
     * @param glf the value for accout_ant.GLF
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setGlf(String glf) {
        this.glf = glf == null ? null : glf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.QTF
     *
     * @return the value of accout_ant.QTF
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getQtf() {
        return qtf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.QTF
     *
     * @param qtf the value for accout_ant.QTF
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setQtf(String qtf) {
        this.qtf = qtf == null ? null : qtf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.SJ
     *
     * @return the value of accout_ant.SJ
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getSj() {
        return sj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.SJ
     *
     * @param sj the value for accout_ant.SJ
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setSj(String sj) {
        this.sj = sj == null ? null : sj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.JE
     *
     * @return the value of accout_ant.JE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getJe() {
        return je;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.JE
     *
     * @param je the value for accout_ant.JE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setJe(String je) {
        this.je = je == null ? null : je.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.SL
     *
     * @return the value of accout_ant.SL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getSl() {
        return sl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.SL
     *
     * @param sl the value for accout_ant.SL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setSl(String sl) {
        this.sl = sl == null ? null : sl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.YHJE
     *
     * @return the value of accout_ant.YHJE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getYhje() {
        return yhje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.YHJE
     *
     * @param yhje the value for accout_ant.YHJE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setYhje(String yhje) {
        this.yhje = yhje == null ? null : yhje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.SSJE
     *
     * @return the value of accout_ant.SSJE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getSsje() {
        return ssje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.SSJE
     *
     * @param ssje the value for accout_ant.SSJE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setSsje(String ssje) {
        this.ssje = ssje == null ? null : ssje.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.JDR
     *
     * @return the value of accout_ant.JDR
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getJdr() {
        return jdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.JDR
     *
     * @param jdr the value for accout_ant.JDR
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setJdr(String jdr) {
        this.jdr = jdr == null ? null : jdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.DELETE_STATUS
     *
     * @return the value of accout_ant.DELETE_STATUS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.DELETE_STATUS
     *
     * @param deleteStatus the value for accout_ant.DELETE_STATUS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.LXR
     *
     * @return the value of accout_ant.LXR
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getLxr() {
        return lxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.LXR
     *
     * @param lxr the value for accout_ant.LXR
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setLxr(String lxr) {
        this.lxr = lxr == null ? null : lxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.CUST_TEL
     *
     * @return the value of accout_ant.CUST_TEL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getCustTel() {
        return custTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.CUST_TEL
     *
     * @param custTel the value for accout_ant.CUST_TEL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setCustTel(String custTel) {
        this.custTel = custTel == null ? null : custTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.CAR_TYPE
     *
     * @return the value of accout_ant.CAR_TYPE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getCarType() {
        return carType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.CAR_TYPE
     *
     * @param carType the value for accout_ant.CAR_TYPE
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setCarType(String carType) {
        this.carType = carType == null ? null : carType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.BALANCE_STATUS
     *
     * @return the value of accout_ant.BALANCE_STATUS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getBalanceStatus() {
        return balanceStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.BALANCE_STATUS
     *
     * @param balanceStatus the value for accout_ant.BALANCE_STATUS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setBalanceStatus(String balanceStatus) {
        this.balanceStatus = balanceStatus == null ? null : balanceStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.COM_NAME
     *
     * @return the value of accout_ant.COM_NAME
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getComName() {
        return comName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.COM_NAME
     *
     * @param comName the value for accout_ant.COM_NAME
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setComName(String comName) {
        this.comName = comName == null ? null : comName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.ADDRESS
     *
     * @return the value of accout_ant.ADDRESS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.ADDRESS
     *
     * @param address the value for accout_ant.ADDRESS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.BANK_NAME
     *
     * @return the value of accout_ant.BANK_NAME
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.BANK_NAME
     *
     * @param bankName the value for accout_ant.BANK_NAME
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.COM_ACC_NO
     *
     * @return the value of accout_ant.COM_ACC_NO
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getComAccNo() {
        return comAccNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.COM_ACC_NO
     *
     * @param comAccNo the value for accout_ant.COM_ACC_NO
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setComAccNo(String comAccNo) {
        this.comAccNo = comAccNo == null ? null : comAccNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.COM_TEL
     *
     * @return the value of accout_ant.COM_TEL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getComTel() {
        return comTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.COM_TEL
     *
     * @param comTel the value for accout_ant.COM_TEL
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setComTel(String comTel) {
        this.comTel = comTel == null ? null : comTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.COM_LXR
     *
     * @return the value of accout_ant.COM_LXR
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getComLxr() {
        return comLxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.COM_LXR
     *
     * @param comLxr the value for accout_ant.COM_LXR
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setComLxr(String comLxr) {
        this.comLxr = comLxr == null ? null : comLxr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column accout_ant.REMARKS
     *
     * @return the value of accout_ant.REMARKS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column accout_ant.REMARKS
     *
     * @param remarks the value for accout_ant.REMARKS
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }
}