package com.computech.pojo;

public class Employee {
    

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_id
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    private Integer empId;
    
    private String loginName;

    public String getLoginName() {
		return loginName;
	}

	public void setLoginName(String loginName) {
		this.loginName = loginName == null ? null : loginName.trim();
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_name
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id_card
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    private String idCard;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.delete_status
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    private String deleteStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.password
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_id
     *
     * @return the value of employee.emp_id
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_id
     *
     * @param empId the value for employee.emp_id
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_name
     *
     * @return the value of employee.emp_name
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_name
     *
     * @param empName the value for employee.emp_name
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id_card
     *
     * @return the value of employee.id_card
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id_card
     *
     * @param idCard the value for employee.id_card
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.delete_status
     *
     * @return the value of employee.delete_status
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    public String getDeleteStatus() {
        return deleteStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.delete_status
     *
     * @param deleteStatus the value for employee.delete_status
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    public void setDeleteStatus(String deleteStatus) {
        this.deleteStatus = deleteStatus == null ? null : deleteStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.password
     *
     * @return the value of employee.password
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.password
     *
     * @param password the value for employee.password
     *
     * @mbg.generated Thu Aug 16 13:45:15 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }
}