package com.computech.pojo;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ciuser.CUST_NO
     *
     * @mbg.generated Mon Jun 11 10:30:43 CST 2018
     */
    private Integer custNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ciuser.CUST_NAME
     *
     * @mbg.generated Mon Jun 11 10:30:43 CST 2018
     */
    private String custName;

    public User() {
		super();
	}

	@Override
	public String toString() {
		return "User [custNo=" + custNo + ", custName=" + custName + ", custTel=" + custTel + ", custLxr=" + custLxr
				+ "]";
	}

	public User(Integer custNo, String custName, String custTel, String custLxr) {
		super();
		this.custNo = custNo;
		this.custName = custName;
		this.custTel = custTel;
		this.custLxr = custLxr;
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ciuser.CUST_TEL
     *
     * @mbg.generated Mon Jun 11 10:30:43 CST 2018
     */
    private String custTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ciuser.CUST_LXR
     *
     * @mbg.generated Mon Jun 11 10:30:43 CST 2018
     */
    private String custLxr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ciuser.CUST_NO
     *
     * @return the value of ciuser.CUST_NO
     *
     * @mbg.generated Mon Jun 11 10:30:43 CST 2018
     */
    public Integer getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ciuser.CUST_NO
     *
     * @param custNo the value for ciuser.CUST_NO
     *
     * @mbg.generated Mon Jun 11 10:30:43 CST 2018
     */
    public void setCustNo(Integer custNo) {
        this.custNo = custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ciuser.CUST_NAME
     *
     * @return the value of ciuser.CUST_NAME
     *
     * @mbg.generated Mon Jun 11 10:30:43 CST 2018
     */
    public String getCustName() {
        return custName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ciuser.CUST_NAME
     *
     * @param custName the value for ciuser.CUST_NAME
     *
     * @mbg.generated Mon Jun 11 10:30:43 CST 2018
     */
    public void setCustName(String custName) {
        this.custName = custName == null ? null : custName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ciuser.CUST_TEL
     *
     * @return the value of ciuser.CUST_TEL
     *
     * @mbg.generated Mon Jun 11 10:30:43 CST 2018
     */
    public String getCustTel() {
        return custTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ciuser.CUST_TEL
     *
     * @param custTel the value for ciuser.CUST_TEL
     *
     * @mbg.generated Mon Jun 11 10:30:43 CST 2018
     */
    public void setCustTel(String custTel) {
        this.custTel = custTel == null ? null : custTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ciuser.CUST_LXR
     *
     * @return the value of ciuser.CUST_LXR
     *
     * @mbg.generated Mon Jun 11 10:30:43 CST 2018
     */
    public String getCustLxr() {
        return custLxr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ciuser.CUST_LXR
     *
     * @param custLxr the value for ciuser.CUST_LXR
     *
     * @mbg.generated Mon Jun 11 10:30:43 CST 2018
     */
    public void setCustLxr(String custLxr) {
        this.custLxr = custLxr == null ? null : custLxr.trim();
    }
}