package com.computech.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import com.computech.dto.AccoutAntCondition;
import com.computech.pojo.AccoutAnt;

@Repository
@Mapper
public interface AccoutAntMapper {
	
	
	/**
	 * 
	 */
	long selectCountByAccoutAnt(@Param("condition") AccoutAntCondition accoutAntCondition);
	
	
	List<AccoutAnt> selectByAccoutAnt(@Param("condition") AccoutAntCondition accoutAntCondition,
                                      @Param("index") int index, @Param("pageSize") int pageSize);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accout_ant
     *
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    int deleteByPrimaryKey(String accNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accout_ant
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    int insert(AccoutAnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accout_ant
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    int insertSelective(AccoutAnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accout_ant
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    AccoutAnt selectByPrimaryKey(String accNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accout_ant
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    int updateByPrimaryKeySelective(AccoutAnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accout_ant
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(AccoutAnt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accout_ant
     *
     * @mbg.generated Thu Jun 14 08:44:02 CST 2018
     */
    int updateByPrimaryKey(AccoutAnt record);
}